---
output:
  md_document:
    variant: markdown_github
---

# Purpose

Setup of GitHub to check code and graphs


```{r, results='hide', message=FALSE, warning=FALSE}

rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(tidyverse)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

Regression table for the pooled OLS of the dataset

```{r, results = 'asis', message=FALSE, warning=FALSE}
Model_Data <- Data_setup(data_loc = "data/Data_PWT.csv")

OLS_Mods <- OlsonNames(data = Model_Data)

```


```{r, results = 'asis', message=FALSE, warning=FALSE}
Pool <- Pooled_OLS(data = Model_Data)
stargazer(Pool_OLS_reg, "text", out = "pooled_table.html")
```

Regression table for a two way fixed effects model

```{r, results = 'asis', message=FALSE, warning=FALSE}
Two_Way <- Two_Way_Fix_Eff(data = Model_Data)
stargazer(Two_Way, "text", out = "Two_Way_table.html")
```


